rhbase_firewall_allow_services:
  - http
  - https

httpd_scripting: 'php'

mariadb_databases:
  - name: wordpress

mariadb_users:
  - name: Maarten
    password: letmein
    priv: wordpress.*:ALL,GRANT
    state: present

mariadb_root_password: letmein

wordpress_database: wordpress
wordpress_user: Maarten
wordpress_password: letmein

#httpd_SSLCertificateFile:
#httpd_SSLCertificateKeyFile:
